### ISSUE TITLE
Why does this need your username and password?

### ISSUE THREAD

**Issue by GoatGod64** [GordoLeal/GordoDownpatch#1]
just asking

**Comment by GordoLeal** [comment]
bruh, why i only received the notification for this when you closed it? whatever github.

This is just a small .bat file that calls for DepotDownloader commands: https://github.com/SteamRE/DepotDownloader
i made it to be easy for people that didn't know how to use depot downloader.
i haven't updated this in years, so probably is better to do this directly with depot downloader.

you can ask for help on the bfbbr discord: https://discord.com/invite/8BKC3US
